// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/core/model/message.proto

package model

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MessageHeader struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ParentID             string   `protobuf:"bytes,2,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Sync                 bool     `protobuf:"varint,4,opt,name=Sync,proto3" json:"Sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d87fc56ef8153b7, []int{0}
}
func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MessageHeader) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *MessageHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageHeader) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

type MessageRoute struct {
	Source               string    `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Group                string    `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`
	Operation            string    `protobuf:"bytes,3,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Resource             *Resource `protobuf:"bytes,4,opt,name=Resource,proto3" json:"Resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageRoute) Reset()         { *m = MessageRoute{} }
func (m *MessageRoute) String() string { return proto.CompactTextString(m) }
func (*MessageRoute) ProtoMessage()    {}
func (*MessageRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d87fc56ef8153b7, []int{1}
}
func (m *MessageRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRoute.Unmarshal(m, b)
}
func (m *MessageRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRoute.Marshal(b, m, deterministic)
}
func (m *MessageRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRoute.Merge(m, src)
}
func (m *MessageRoute) XXX_Size() int {
	return xxx_messageInfo_MessageRoute.Size(m)
}
func (m *MessageRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRoute.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRoute proto.InternalMessageInfo

func (m *MessageRoute) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MessageRoute) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *MessageRoute) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *MessageRoute) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type Resource struct {
	ResourceType         string   `protobuf:"bytes,1,opt,name=ResourceType,proto3" json:"ResourceType,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d87fc56ef8153b7, []int{2}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Resource) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	Header               *MessageHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Router               *MessageRoute  `protobuf:"bytes,2,opt,name=Router,proto3" json:"Router,omitempty"`
	Content              []byte         `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d87fc56ef8153b7, []int{3}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetRouter() *MessageRoute {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Test struct {
	Detail               *types.Any `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d87fc56ef8153b7, []int{4}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetDetail() *types.Any {
	if m != nil {
		return m.Detail
	}
	return nil
}

type Detail struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d87fc56ef8153b7, []int{5}
}
func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (m *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(m, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageHeader)(nil), "model.MessageHeader")
	proto.RegisterType((*MessageRoute)(nil), "model.MessageRoute")
	proto.RegisterType((*Resource)(nil), "model.Resource")
	proto.RegisterType((*Message)(nil), "model.Message")
	proto.RegisterType((*Test)(nil), "model.Test")
	proto.RegisterType((*Detail)(nil), "model.Detail")
}

func init() { proto.RegisterFile("pkg/core/model/message.proto", fileDescriptor_1d87fc56ef8153b7) }

var fileDescriptor_1d87fc56ef8153b7 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x53, 0xfe, 0x14, 0x18, 0xaa, 0x26, 0x2b, 0x31, 0x95, 0x70, 0x20, 0x3d, 0x91, 0x60,
	0xda, 0x04, 0x7d, 0x01, 0xb5, 0x89, 0x72, 0x30, 0x9a, 0x85, 0x17, 0x58, 0xe8, 0xd8, 0x10, 0x69,
	0xb7, 0xd9, 0x6e, 0x0f, 0xbd, 0x78, 0xf5, 0xb5, 0x4d, 0x67, 0xb7, 0x10, 0x6e, 0x33, 0xdf, 0x7e,
	0xb3, 0xbf, 0xfd, 0x66, 0x61, 0x56, 0xfc, 0xa4, 0xd1, 0x5e, 0x2a, 0x8c, 0x32, 0x99, 0xe0, 0x31,
	0xca, 0xb0, 0x2c, 0x45, 0x8a, 0x61, 0xa1, 0xa4, 0x96, 0xac, 0x4f, 0xe2, 0xf4, 0x3e, 0x95, 0x32,
	0x3d, 0x62, 0x44, 0xe2, 0xae, 0xfa, 0x8e, 0x44, 0x5e, 0x1b, 0x47, 0x90, 0xc1, 0xd5, 0x87, 0x19,
	0x79, 0x47, 0x91, 0xa0, 0x62, 0xd7, 0xd0, 0x59, 0xc7, 0xbe, 0x33, 0x77, 0x16, 0x23, 0xde, 0x59,
	0xc7, 0x6c, 0x0a, 0xc3, 0x2f, 0xa1, 0x30, 0xd7, 0xeb, 0xd8, 0xef, 0x90, 0x7a, 0xea, 0xd9, 0x0c,
	0x46, 0xdb, 0x43, 0x86, 0xa5, 0x16, 0x59, 0xe1, 0x77, 0xe7, 0xce, 0xa2, 0xcb, 0xcf, 0x02, 0x63,
	0xd0, 0xdb, 0xd4, 0xf9, 0xde, 0xef, 0xcd, 0x9d, 0xc5, 0x90, 0x53, 0x1d, 0xfc, 0x39, 0xe0, 0x59,
	0x1e, 0x97, 0x95, 0x46, 0x76, 0x07, 0xee, 0x46, 0x56, 0x6a, 0x8f, 0x16, 0x69, 0x3b, 0x36, 0x81,
	0xfe, 0x9b, 0x92, 0x55, 0x61, 0x99, 0xa6, 0x69, 0x80, 0x9f, 0x05, 0x2a, 0xa1, 0x0f, 0x32, 0x27,
	0xe0, 0x88, 0x9f, 0x05, 0xb6, 0x84, 0x21, 0xc7, 0xd2, 0xdc, 0xd6, 0x40, 0xc7, 0xab, 0x9b, 0x90,
	0x16, 0x10, 0xb6, 0x32, 0x3f, 0x19, 0x82, 0x97, 0xb3, 0x99, 0x05, 0xe0, 0xb5, 0xf5, 0xb6, 0x2e,
	0xda, 0xa7, 0x5c, 0x68, 0x4d, 0x9a, 0x58, 0x68, 0x41, 0xef, 0xf1, 0x38, 0xd5, 0xc1, 0x2f, 0x0c,
	0x6c, 0x18, 0xf6, 0x00, 0xae, 0x59, 0x20, 0x0d, 0x8f, 0x57, 0x13, 0x4b, 0xbe, 0x58, 0x2e, 0xb7,
	0x1e, 0xb6, 0x04, 0x97, 0xe2, 0x2b, 0xba, 0x6e, 0xbc, 0xba, 0xbd, 0x74, 0xd3, 0x19, 0xb7, 0x16,
	0xe6, 0xc3, 0xe0, 0x55, 0xe6, 0x1a, 0x73, 0x4d, 0x91, 0x3d, 0xde, 0xb6, 0xc1, 0x13, 0xf4, 0xb6,
	0x58, 0xea, 0x06, 0x9e, 0xa0, 0x16, 0x87, 0xe3, 0x09, 0x6e, 0x3e, 0x3c, 0x6c, 0x3f, 0x3c, 0x7c,
	0xce, 0x6b, 0x6e, 0x3d, 0xc1, 0x0c, 0xdc, 0x98, 0xaa, 0x26, 0x53, 0xd2, 0x64, 0x32, 0x79, 0xa9,
	0xde, 0xb9, 0x34, 0xf3, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x03, 0x5d, 0x01, 0x5b, 0x59, 0x02,
	0x00, 0x00,
}
